version: 2.1
tagged_build_filters: &tagged_build_filters
  branches:
    ignore: /.*/
  tags:
    only: /v[0-9]+\.[0-9]+\.[0-9]+/
test_build_filters: &test_build_filters
  branches:
    only: /.*/
  tags:
    ignore: /v[0-9]+\.[0-9]+\.[0-9]+/
jobs:
  test:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: "Install test dependencies"
          command: |
            go get -u golang.org/x/lint/golint
            go get github.com/mattn/goveralls
      - run:
          name: "Lint"
          command: |
            golint -set_exit_status **/*.go
      - run:
          name: "Run tests"
          command: |
            make testcov
            goveralls -coverprofile=coverage/coverage.out -service=circleci -repotoken $COVERALLS_REPO_TOKEN
      - store_artifacts:
          path: coverage
workflows:
  update:
    jobs:
      - test:
          filters: *tagged_build_filters
          context:
            - Terraform Provider Context
  test:
    jobs:
      - test:
          filters: *test_build_filters
          context:
            - Terraform Provider Context
